// Generated by tools/build-site.mjs. Never edit by hand.
const CACHE = 'edusphere-' + "1791132370032".replace(/[^A-Za-z0-9]+/g, '-');
const ASSETS = ['./', './index.html', './manifest.webmanifest', './icons/icon-192.png', './icons/icon-512.png', './icons/icon-512-maskable.png', './icons/icon-180.png'];
self.addEventListener('install', (e) => { e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting())); });
self.addEventListener('activate', (e) => { e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (url.origin !== self.location.origin || e.request.method !== 'GET') return;
  const isPage = e.request.mode === 'navigate' || url.pathname.endsWith('/') || url.pathname.endsWith('/index.html');
  const keep = (res) => { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(e.request, copy)); return res; };
  if (isPage) { e.respondWith(fetch(e.request).then(keep).catch(() => caches.match(e.request).then((r) => r || caches.match('./index.html')))); return; }
  e.respondWith(caches.match(e.request).then((r) => r || fetch(e.request).then(keep)));
});
