// The Wise Human. Copyright (c) 2026. Source-available; not for reuse. See LICENSE.md.
// The doubling program (2026-09-24, Mikey): every module story twice its old length, still the Gladwell arc, with up to six
// pictures. Targets by band: pre-K 60 words and four pictures, K to 2 100 and five, grade 3 up 240 and six; a story
// below its target is listed here.
// Run: node tools/story-length.mjs > docs/STORY-LENGTH.md
import { MODULES, getCourse } from '../src/logic.mjs';
import { STORIES, COURSE_STORIES } from '../src/stories.mjs';
const target = (g) => (['PK3', 'PK4'].includes(g) ? 60 : ['K', '1', '2'].includes(g) ? 100 : 240);
const pictures = (g) => (['PK3', 'PK4'].includes(g) ? 4 : ['K', '1', '2'].includes(g) ? 5 : 6);   // 2026-09-24, Mikey: fewer for the shortest stories
const rows = []; let total = 0;
for (const m of MODULES) { const st = STORIES[m.id]; const c = getCourse(m.courseId); if (!st || !c) continue; total++; const words = st.words.join(' ').split(/\s+/).filter(Boolean).length; const pics = 1 + (st.more || []).length; if (words < target(c.grade) || pics < pictures(c.grade)) rows.push([c.grade, c.subject, m.id, words, target(c.grade), `${pics} of ${pictures(c.grade)}`]); }
console.log(`# Stories still to double\n\nGenerated by tools/story-length.mjs. ${rows.length} of ${total} module stories are under their length target or short of their picture count.\n\n| Grade | Subject | Module | Words | Target | Pictures |\n|---|---|---|---|---|---|`);
for (const r of rows) console.log(`| ${r.join(' | ')} |`);
// Long stories are doubled too (2026-09-24, Mikey): 400 words and six pictures, done after each grade's short stories.
const longRows = Object.entries(COURSE_STORIES).map(([id, cs]) => { const c = getCourse(id); const words = cs.words.join(' ').split(/\s+/).filter(Boolean).length; const pics = 1 + (cs.more || []).length; return [c ? c.grade : '?', c ? c.subject : '?', id, words, 400, `${pics} of 6`, words < 400 || pics < 6]; }).filter((r) => r[6]);
console.log(`\n## Long stories\n\n${longRows.length} of ${Object.keys(COURSE_STORIES).length} long stories are under 400 words or short of six pictures. Each grade's long stories are doubled once its short stories are done.\n\n| Grade | Subject | Course | Words | Target | Pictures |\n|---|---|---|---|---|---|`);
for (const r of longRows) console.log(`| ${r.slice(0, 6).join(' | ')} |`);
