// The Wise Human. Copyright (c) 2026. Source-available; not for reuse. See LICENSE.md.
// Lists the module stories that fall short of the Miniature Gladwell Method (2026-09-23, Mikey): from grade 3 up a story
// needs the four-step arc (an anchor, a friction point, the insight, the echo), so at least four paragraphs and eighty
// words; early years stories may stay short. Run: node tools/story-arc.mjs > docs/THIN-STORIES.md
import * as L from '../src/logic.mjs';
import { STORIES } from '../src/stories.mjs';
const early = new Set(['PK3', 'PK4', 'K', '1', '2']);
const rows = [];
for (const m of L.MODULES) {
  const st = STORIES[m.id]; const c = L.getCourse(m.courseId); if (!st || !c || early.has(c.grade)) continue;
  const words = st.words.join(' ').split(/\s+/).filter(Boolean).length;
  if (words < 80) rows.push([c.grade, c.subject, m.id, st.words.length, words]);
}
const total = L.MODULES.filter((m) => STORIES[m.id] && !early.has((L.getCourse(m.courseId) || {}).grade)).length;
console.log('# Stories still to bring up to the arc\n');
console.log(`Generated by tools/story-arc.mjs. Grade 3 and up: ${rows.length} of ${total} stories are under eighty words (three terse lines rather than a story).\n`);
console.log('| Grade | Subject | Module | Paragraphs | Words |\n|---|---|---|---|---|');
for (const r of rows) console.log(`| ${r.join(' | ')} |`);
